### PR TITLE
Update deployment.yaml

### PR DESCRIPTION
**Pull request by gh-codeowners-sample**
test

### CODE REVIEW

**Review by mszostok — APPROVED** [review]

**Review by mszostok — COMMENTED** [review]
.  Kustomization diffing...: running dry-run\n.. Kustomization diffing...: processing inventory\n✓  Kustomization diffing...\n► Deployment/default/podinfo drifted\n\nmetadata.generation\n  ± value change\n    - 2\n    + 3\n\nspec.minReadySeconds\n  ± value change\n    - 3\n    + 30\n\n

**Review by mszostok — COMMENTED** [review]
#### Flux Kustomization changes

Merging this pull request will trigger updates to the `labs` cluster, introducing the following changes:

<details open><summary>Output</summary>
<p>


```diff
► Deployment/default/podinfo drifted

metadata.generation
  ± value change
    - 2
    + 3

spec.minReadySeconds
  ± value change
    - 3
    + 30
```

</p>
</details> 


_Comment generated using [Botkube Flux](https://docs.botkube.io/configuration/executor/flux) integration._

**Review by mszostok — APPROVED** [review]

**Review by mszostok — APPROVED** [review]

**Review by mszostok — APPROVED** [review]

**Comment by mszostok** [comment]
#### Flux Kustomization changes

Merging this pull request will introduce the following changes:

<details open><summary>Output</summary>
<p>


```
► Deployment/default/podinfo drifted

metadata.generation
  ± value change
    - 2
    + 3

spec.minReadySeconds
  ± value change
    - 3
    + 30
```

</p>
</details> 


_Comment created via [Botkube Flux](https://docs.botkube.io/configuration/executor/flux) integration._

**Comment by mszostok** [comment]
#### Flux Kustomization changes

Merging this pull request will introduce the following changes:

<details open><summary>Output</summary>
<p>


```
► Deployment/default/podinfo drifted

metadata.generation
  ± value change
    - 2
    + 3

spec.minReadySeconds
  ± value change
    - 3
    + 30
```

</p>
</details> 


_Comment created via [Botkube Flux](https://docs.botkube.io/configuration/executor/flux) integration._

**Comment by mszostok** [comment]
#### Flux Kustomization changes

Merging this pull request will introduce the following changes:

<details open><summary>Output</summary>
<p>


```
► Deployment/default/podinfo drifted

metadata.generation
  ± value change
    - 2
    + 3

spec.minReadySeconds
  ± value change
    - 3
    + 30
```

</p>
</details> 


_Comment created via [Botkube Flux](https://docs.botkube.io/configuration/executor/flux) integration._

**Comment by mszostok** [comment]
#### Flux Kustomization changes

Merging this pull request will introduce the following changes:

<details open><summary>Output</summary>
<p>


```
► Deployment/default/podinfo drifted

metadata.generation
  ± value change
    - 2
    + 3

spec.minReadySeconds
  ± value change
    - 3
    + 30
```

</p>
</details> 


_Comment created via [Botkube Flux](https://docs.botkube.io/configuration/executor/flux) integration._

**Review by mszostok — APPROVED** [review]

**Review by mszostok — APPROVED** [review]

**Comment by mszostok** [comment]
#### Flux Kustomization changes

Merging this pull request will introduce the following changes:

<details open><summary>Output</summary>
<p>


```
► Deployment/default/podinfo drifted

metadata.generation
  ± value change
    - 2
    + 3

spec.minReadySeconds
  ± value change
    - 3
    + 30
```

</p>
</details> 


_Comment created via [Botkube Flux](https://docs.botkube.io/configuration/executor/flux) integration._

**Comment by huseyinbabal** [comment]
#### Flux Kustomization changes

Merging this pull request will introduce the following changes:

<details open><summary>Output</summary>
<p>


```
► Deployment/default/podinfo drifted

metadata.generation
  ± value change
    - 2
    + 3

spec.minReadySeconds
  ± value change
    - 3
    + 30
```

</p>
</details> 


_Comment created via [Botkube Flux](https://docs.botkube.io/configuration/executor/flux) integration._

**Comment by mszostok** [comment]
#### Flux Kustomization changes

Merging this pull request will introduce the following changes:

<details open><summary>Output</summary>
<p>


```
► Deployment/default/podinfo drifted

metadata.generation
  ± value change
    - 2
    + 3

spec.minReadySeconds
  ± value change
    - 3
    + 30
```

</p>
</details> 


_Comment created via [Botkube Flux](https://docs.botkube.io/configuration/executor/flux) integration._

**Comment by mszostok** [comment]
#### Flux Kustomization changes

Merging this pull request will introduce the following changes:

<details open><summary>Output</summary>
<p>


```
► Deployment/default/podinfo drifted

metadata.generation
  ± value change
    - 2
    + 3

spec.minReadySeconds
  ± value change
    - 3
    + 30
```

</p>
</details> 


_Comment created via [Botkube Flux](https://docs.botkube.io/configuration/executor/flux) integration._

**Comment by mszostok** [comment]
#### Flux Kustomization changes

Merging this pull request will introduce the following changes:

<details open><summary>Output</summary>
<p>


```
► Deployment/default/podinfo drifted

metadata.generation
  ± value change
    - 2
    + 3

spec.minReadySeconds
  ± value change
    - 3
    + 30
```

</p>
</details> 


_Comment created via [Botkube Flux](https://docs.botkube.io/configuration/executor/flux) integration._

**Comment by mszostok** [comment]
#### Flux Kustomization changes

Merging this pull request will introduce the following changes:

<details open><summary>Output</summary>
<p>


```
► Deployment/default/podinfo drifted

metadata.generation
  ± value change
    - 2
    + 3

spec.minReadySeconds
  ± value change
    - 3
    + 30
```

</p>
</details> 


_Comment created via [Botkube Flux](https://docs.botkube.io/configuration/executor/flux) integration._

**Review by mszostok — DISMISSED** [review]

**Review by mszostok — APPROVED** [review]

**Pull request closed without merging**
